apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJpRENDQVMrZ0F3SUJBZ0lRSHF4TWpJWE1iRjg2bGxma1lSWm10VEFLQmdncWhrak9QUVFEQWpBVk1STXcKRVFZRFZRUUtFd3ByZFdKbGNtNWxkR1Z6TUI0WERUSTJNRFF3TmpFeE1UY3pNVm9YRFRNMk1EUXdNekV4TVRjegpNVm93RlRFVE1CRUdBMVVFQ2hNS2EzVmlaWEp1WlhSbGN6QlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VICkEwSUFCSnhya1lCVTZEQlRqU3doVTFhL0FQdGJaa2tJUXVSQWNsWFJwRXNuSUNIa29xRzVmb1ZWRkYvVjZDZGIKQXE3TVFFMDJMTkFydEZEdTNVQXUzMFNraXZtallUQmZNQTRHQTFVZER3RUIvd1FFQXdJQ2hEQWRCZ05WSFNVRQpGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFCkZnUVVLYlducUFXcDM2YkFOM0pzY1lOQ0t0c1ZBNlV3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnSUhhVVlDQXcKbGduczhnSzJJSnhNNEZ1disvWVg5cC9pN2JwUm5ZRnpLazRDSURHWmlJY3EyN2xESllTTHNEWWNHRFIyNEpRTgpjalA1QlF4UGdNZ3hXMk5HCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://192.168.1.104:6443
  name: kube-syd
contexts:
- context:
    cluster: kube-syd
    namespace: default
    user: admin@kube-syd
  name: admin@kube-syd
current-context: admin@kube-syd
kind: Config
users:
- name: admin@kube-syd
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJoRENDQVNxZ0F3SUJBZ0lRUWFwVDZoOHNscWRZTEFENnIwdm9CVEFLQmdncWhrak9QUVFEQWpBVk1STXcKRVFZRFZRUUtFd3ByZFdKbGNtNWxkR1Z6TUI0WERUSTJNRFF3TmpFeE1UZzBNVm9YRFRJM01EUXdOakV4TVRnMQpNVm93S1RFWE1CVUdBMVVFQ2hNT2MzbHpkR1Z0T20xaGMzUmxjbk14RGpBTUJnTlZCQU1UQldGa2JXbHVNRmt3CkV3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFdkloS0Nib2dsZjlXdVZ6M05MYVRZbXBCSEVjTUFMV0gKaU5BbWxvN3gvcFZQNnpJWi9mYzcvRmoyQkJleDNtVzZMdlNYSFU2cFprWTBod2Z5djlTZkU2TklNRVl3RGdZRApWUjBQQVFIL0JBUURBZ1dnTUJNR0ExVWRKUVFNTUFvR0NDc0dBUVVGQndNQ01COEdBMVVkSXdRWU1CYUFGQ20xCnA2Z0ZxZCttd0RkeWJIR0RRaXJiRlFPbE1Bb0dDQ3FHU000OUJBTUNBMGdBTUVVQ0lRQ2pHN29ydFR3QXpKcUIKRE1zSHI4Rm5vNWZLTmFzQmpWK0NOeUlHR2YvaEZRSWdCNmlUNmExVjRTMCtoZnF3VWlwei9xR2dReFAxSDdTWQpmaXF5bHJFNFRqMD0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUtuRDlWUDA2ZS9PNjlQeUh1Y0FkZExSeFF4UHVlRFFCM0xpK3dZb3BmUkJvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFdkloS0Nib2dsZjlXdVZ6M05MYVRZbXBCSEVjTUFMV0hpTkFtbG83eC9wVlA2eklaL2ZjNwovRmoyQkJleDNtVzZMdlNYSFU2cFprWTBod2Z5djlTZkV3PT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
